services:
  jupyter:
    build: .
    container_name: mspr_python
    ports:
      - "8888:8888"
    volumes:
      - ./data:/app/data
      - ./notebooks:/app/notebooks
      - ./outputs:/app/outputs
    restart: unless-stopped
